#!/bin/bash

set -e

OPTS+=" -Pskip-static-checks"
OPTS+=" -Dsurefire.rerunFailingTestsCount=0"
[[ $@ =~ "-q" ]] && OPTS+=" -Dsurefire.trimStackTrace=true"

OPTS+=" -pl sql -Dtest=SqlQuidemTest"

echo mvn $OPTS install "$@"

#-Dquidem.filter=*join*
#-Dquidem.overwrite

