#!/bin/bash
set -e

OPTS+=" -Pskip-static-checks"
OPTS+=" -Dquidem.overwriteX"
OPTS+=" -Dsurefire.trimStackTrace=true"
OPTS+=" -Dsurefire.rerunFailingTestsCount=0"

OPTS+=" -pl sql -Dtest=SqlQuidemTest"

mvn $OPTS install "$@"

#-Dquidem.filter=*join*
#-Dquidem.overwrite

