#!/bin/bash

set -e

OPTS+=" -Pskip-static-checks"
OPTS+=" -Dsurefire.rerunFailingTestsCount=0"
OPTS+=" -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugin.surefire.SurefirePlugin=INFO"
[[ $@ =~ "-q" ]] && OPTS+=" -Dsurefire.trimStackTrace=true"

OPTS+=" -pl sql -Dtest=SqlQuidemTest"
OPTS+=" org.apache.maven.plugins:maven-surefire-plugin:test"

mvn "$@" $OPTS

#-Dquidem.filter=*join*
#-Dquidem.overwrite

